PREFIX om-owl: <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#>
PREFIX weather: <http://knoesis.wright.edu/ssw/ont/weather.owl#>

SELECT DISTINCT ?sensor ?observation ?observation2 
#?v1 ?v2   
FROM NAMED STREAM <http://cwi.nl/SRBench/observations> [NOW - 2 S SLIDE 1 S]
WHERE {

?observation a weather:TemperatureObservation.
  ?observation om-owl:observedBy ?sensor.
#               om-owl:observedProperty weather:AirTemperature;
#               om-owl:result ?result.
#  ?result om-owl:floatValue ?v1.
  ?observation2 om-owl:observedBy ?sensor.
  ?observation2 a weather:WindSpeedObservation.
#               om-owl:observedProperty weather:RelativeHumidity;
#               om-owl:result ?result2.
#  ?result2 om-owl:floatValue ?v2.  
}