PREFIX om-owl: <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#>
PREFIX weather: <http://knoesis.wright.edu/ssw/ont/weather.owl#>
PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#> 

SELECT DISTINCT ?sensor ?observation 
FROM NAMED STREAM <http://cwi.nl/SRBench/observations> [NOW - 10 S]
WHERE {
  ?observation om-owl:observedBy ?sensor;
               a weather:TemperatureObservation.
  GRAPH <http://papa.com/static> {
  ?sensor om-owl:processLocation ?loc.
  ?loc wgs84:lat ?lat.
  ?loc wgs84:lon ?lon.
  }
}