PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX qudt: <http://data.nasa.gov/qudt/owl/qudt#>
PREFIX propWindSpeed: <http://sweet.jpl.nasa.gov/2.1/propWindSpeed.owl#> 
SELECT ?windspeed ?instant 
#FROM NAMED STREAM <http://semsorgrid4env.eu/ns#ccometeo.srdf> 
#[NOW - 10 MINUTE TO NOW - 5 MINUTE SLIDE 3 MINUTE] 
WHERE 
{ 
	?WindObs 	a ssn:Observation;
				ssn:observationResultTime ?instant;				
				ssn:observationResult ?result;  
				ssn:observedProperty propWindSpeed:WindSpeed.
	?instant	time:xsdDateTime ?time.
	?result		ssn:hasValue ?value.
	?value		qudt:numericValue ?windspeed.
}
		
