PREFIX ssg: <http://semsorgrid4env.eu/ns#>							
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX cd:  <http://www.semsorgrid4env.eu/ontologies/CoastalDefences.owl#>
PREFIX dul:	<http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX regions: <http://www.semsorgrid4env.eu/ontologies/AdditionalRegions.owl#>
PREFIX swissex: <http://swiss-experiment.ch/metadata#>  
PREFIX quantity: <http://data.nasa.gov/qudt/owl/quantity#>
PREFIX qudt: <http://data.nasa.gov/qudt/owl/qudt#>
PREFIX propPressure: <http://sweet.jpl.nasa.gov/2.1/propPressure.owl#> 
PREFIX propTemperature: <http://sweet.jpl.nasa.gov/2.1/propTemperature.owl#> 
SELECT ?temperature ?sensor ?timestamp ?obs 
FROM NAMED STREAM swissex:WannengratSensors.srdf [NOW - 5 MONTH ] 
WHERE 
{ 
	?obs     	a ssn:Observation;
				ssn:observationResultTime ?instant;				
				ssn:observationResult ?result;
				ssn:observedProperty quantity:ThermodynamicTemperature;
				ssn:observedBy ?sensor.  		
	?instant	time:xsdDateTime ?timestamp.
	?result		ssn:hasValue ?obsresult.
	?obsresult  qudt:numericValue ?temperature.
}
		
