PREFIX om-owl: <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#>
PREFIX weather: <http://knoesis.wright.edu/ssw/ont/weather.owl#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX qu: <http://purl.oclc.org/NET/ssnx/qu/qu#>

SELECT DISTINCT ?observation ?value  
FROM NAMED STREAM <http://cwi.nl/SRBench/observations> [NOW - 1 HOURS]
WHERE {
  ?observation ssn:observedBy ?sensor;
#               ssn:observedProperty weather:AirTemperature;
               ssn:observationResult ?result.
 ?result ssn:numericalValue ?value;
  FILTER (?value > 0.5)  
}