PREFIX cd: <http://semsorgrid4env.eu/ns#>							
PREFIX sb: <http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
SELECT  ?waveheight ?wavets 
FROM NAMED STREAM <http://semsorgrid4env.eu/ns#ccometeo.srdf> 
[invalid] 
WHERE 
{ 
 ?WaveObs a cd:Observation;
   cd:observedProperty cd:WaveHeight.
}
		
