PREFIX om-owl: <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#>
PREFIX oeg-sen: <http://oeg-upm.net/onto/sensordemo/>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX qu: <http://purl.oclc.org/NET/ssnx/qu/qu#>

SELECT DISTINCT ?observation ?value  
FROM NAMED STREAM <http://cwi.nl/SRBench/observations> [NOW - 1 HOURS]
WHERE {
  ?observation a oeg-sen:ThermistorObservation;
               ssn:observationResult ?result.
 ?result ssn:hasValue ?obsValue.               
 ?obsValue qu:numericalValue ?value.
 FILTER (?value > 0.5)  
}