PREFIX om-owl: <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#>
PREFIX oeg-sen: <http://oeg-upm.net/onto/sensordemo/>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX qu: <http://purl.oclc.org/NET/ssnx/qu/qu#>
PREFIX quantity: <http://purl.oclc.org/NET/ssnx/qu/quantity#>
PREFIX dim: <http://purl.oclc.org/NET/ssnx/qu/dim#>
PREFIX unit: <http://purl.oclc.org/NET/ssnx/qu/unit#>
PREFIX cf-feature: <http://purl.oclc.org/NET/ssnx/cf/cf-feature#>
PREFIX cf-property: <http://purl.oclc.org/NET/ssnx/cf/cf-property#>

SELECT DISTINCT ?obsValue ?value  
FROM NAMED STREAM <http://cwi.nl/SRBench/observations> [NOW - 1 HOURS]
WHERE {
 ?observation ssn:observedProperty ?op;
              ssn:observationResult ?result.
 ?result ssn:hasValue ?obsValue.               
 ?obsValue qu:numericalValue ?value;
           qu:unit unit:degreeCelsius.
 FILTER (?value > 0.5)  
}