PREFIX cd: <http://www.semsorgrid4env.eu/ontologies/CoastalDefences.owl#>							
PREFIX sb: <http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>  
SELECT  ?waveheight ?wavets   
FROM NAMED STREAM <http://semsorgrid4env.eu/ccometeo.srdf>
[NOW - 10 MINUTES TO NOW - 5 MINUTES SLIDE 3 MINUTES]    
WHERE 
{ 
 ?WaveObs a ssn:Observation; 
    ssn:observationResult ?waveheight; 
    ssn:observationResultTime ?wavets;
    ssn:observedProperty ?waveProperty.
#    ssn:featureOfInterest ?waveFeature.   
# ?waveProperty a cd:AirPressure. 
 }
		
