/* Generated By:JavaCC: Do not edit this line. SPARQLStrParserConstants.java */
package es.upm.fi.oeg.sparqlstream.parser ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SPARQLStrParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int WS = 7;
  /** RegularExpression Id. */
  int WSC = 8;
  /** RegularExpression Id. */
  int IRIref = 9;
  /** RegularExpression Id. */
  int PNAME_NS = 10;
  /** RegularExpression Id. */
  int PNAME_LN = 11;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 12;
  /** RegularExpression Id. */
  int VAR1 = 13;
  /** RegularExpression Id. */
  int VAR2 = 14;
  /** RegularExpression Id. */
  int LANGTAG = 15;
  /** RegularExpression Id. */
  int A2Z = 16;
  /** RegularExpression Id. */
  int A2ZN = 17;
  /** RegularExpression Id. */
  int KW_A = 18;
  /** RegularExpression Id. */
  int BASE = 19;
  /** RegularExpression Id. */
  int PREFIX = 20;
  /** RegularExpression Id. */
  int SELECT = 21;
  /** RegularExpression Id. */
  int DISTINCT = 22;
  /** RegularExpression Id. */
  int REDUCED = 23;
  /** RegularExpression Id. */
  int DESCRIBE = 24;
  /** RegularExpression Id. */
  int CONSTRUCT = 25;
  /** RegularExpression Id. */
  int ASK = 26;
  /** RegularExpression Id. */
  int LIMIT = 27;
  /** RegularExpression Id. */
  int OFFSET = 28;
  /** RegularExpression Id. */
  int ORDER = 29;
  /** RegularExpression Id. */
  int BY = 30;
  /** RegularExpression Id. */
  int VALUES = 31;
  /** RegularExpression Id. */
  int UNDEF = 32;
  /** RegularExpression Id. */
  int ASC = 33;
  /** RegularExpression Id. */
  int DESC = 34;
  /** RegularExpression Id. */
  int NAMED = 35;
  /** RegularExpression Id. */
  int FROM = 36;
  /** RegularExpression Id. */
  int STREAM = 37;
  /** RegularExpression Id. */
  int WINDOW = 38;
  /** RegularExpression Id. */
  int RANGE = 39;
  /** RegularExpression Id. */
  int SLIDE = 40;
  /** RegularExpression Id. */
  int ADVANCE = 41;
  /** RegularExpression Id. */
  int FIXED = 42;
  /** RegularExpression Id. */
  int TRIPLES = 43;
  /** RegularExpression Id. */
  int PWINDOW = 44;
  /** RegularExpression Id. */
  int START = 45;
  /** RegularExpression Id. */
  int END = 46;
  /** RegularExpression Id. */
  int REGISTER = 47;
  /** RegularExpression Id. */
  int TIMESTAMP = 48;
  /** RegularExpression Id. */
  int RSTREAM = 49;
  /** RegularExpression Id. */
  int DSTREAM = 50;
  /** RegularExpression Id. */
  int ISTREAM = 51;
  /** RegularExpression Id. */
  int MS = 52;
  /** RegularExpression Id. */
  int S = 53;
  /** RegularExpression Id. */
  int HR = 54;
  /** RegularExpression Id. */
  int WHERE = 55;
  /** RegularExpression Id. */
  int AND = 56;
  /** RegularExpression Id. */
  int GRAPH = 57;
  /** RegularExpression Id. */
  int OPTIONAL = 58;
  /** RegularExpression Id. */
  int UNION = 59;
  /** RegularExpression Id. */
  int MINUS_P = 60;
  /** RegularExpression Id. */
  int BIND = 61;
  /** RegularExpression Id. */
  int SERVICE = 62;
  /** RegularExpression Id. */
  int EXISTS = 63;
  /** RegularExpression Id. */
  int NOT = 64;
  /** RegularExpression Id. */
  int AS = 65;
  /** RegularExpression Id. */
  int GROUP = 66;
  /** RegularExpression Id. */
  int HAVING = 67;
  /** RegularExpression Id. */
  int SEPARATOR = 68;
  /** RegularExpression Id. */
  int AGG = 69;
  /** RegularExpression Id. */
  int COUNT = 70;
  /** RegularExpression Id. */
  int MIN = 71;
  /** RegularExpression Id. */
  int MAX = 72;
  /** RegularExpression Id. */
  int SUM = 73;
  /** RegularExpression Id. */
  int AVG = 74;
  /** RegularExpression Id. */
  int STDDEV = 75;
  /** RegularExpression Id. */
  int SAMPLE = 76;
  /** RegularExpression Id. */
  int GROUP_CONCAT = 77;
  /** RegularExpression Id. */
  int FILTER = 78;
  /** RegularExpression Id. */
  int BOUND = 79;
  /** RegularExpression Id. */
  int COALESCE = 80;
  /** RegularExpression Id. */
  int IN = 81;
  /** RegularExpression Id. */
  int IF = 82;
  /** RegularExpression Id. */
  int BNODE = 83;
  /** RegularExpression Id. */
  int IRI = 84;
  /** RegularExpression Id. */
  int URI = 85;
  /** RegularExpression Id. */
  int STR = 86;
  /** RegularExpression Id. */
  int STRLANG = 87;
  /** RegularExpression Id. */
  int STRDT = 88;
  /** RegularExpression Id. */
  int DTYPE = 89;
  /** RegularExpression Id. */
  int LANG = 90;
  /** RegularExpression Id. */
  int LANGMATCHES = 91;
  /** RegularExpression Id. */
  int IS_URI = 92;
  /** RegularExpression Id. */
  int IS_IRI = 93;
  /** RegularExpression Id. */
  int IS_BLANK = 94;
  /** RegularExpression Id. */
  int IS_LITERAL = 95;
  /** RegularExpression Id. */
  int IS_NUMERIC = 96;
  /** RegularExpression Id. */
  int REGEX = 97;
  /** RegularExpression Id. */
  int SAME_TERM = 98;
  /** RegularExpression Id. */
  int RAND = 99;
  /** RegularExpression Id. */
  int ABS = 100;
  /** RegularExpression Id. */
  int CEIL = 101;
  /** RegularExpression Id. */
  int FLOOR = 102;
  /** RegularExpression Id. */
  int ROUND = 103;
  /** RegularExpression Id. */
  int CONCAT = 104;
  /** RegularExpression Id. */
  int SUBSTR = 105;
  /** RegularExpression Id. */
  int STRLEN = 106;
  /** RegularExpression Id. */
  int REPLACE = 107;
  /** RegularExpression Id. */
  int UCASE = 108;
  /** RegularExpression Id. */
  int LCASE = 109;
  /** RegularExpression Id. */
  int ENCODE_FOR_URI = 110;
  /** RegularExpression Id. */
  int CONTAINS = 111;
  /** RegularExpression Id. */
  int STRSTARTS = 112;
  /** RegularExpression Id. */
  int STRENDS = 113;
  /** RegularExpression Id. */
  int STRBEFORE = 114;
  /** RegularExpression Id. */
  int STRAFTER = 115;
  /** RegularExpression Id. */
  int YEAR = 116;
  /** RegularExpression Id. */
  int MONTH = 117;
  /** RegularExpression Id. */
  int DAY = 118;
  /** RegularExpression Id. */
  int HOURS = 119;
  /** RegularExpression Id. */
  int MINUTES = 120;
  /** RegularExpression Id. */
  int SECONDS = 121;
  /** RegularExpression Id. */
  int TIMEZONE = 122;
  /** RegularExpression Id. */
  int TZ = 123;
  /** RegularExpression Id. */
  int NOW = 124;
  /** RegularExpression Id. */
  int MD5 = 125;
  /** RegularExpression Id. */
  int SHA1 = 126;
  /** RegularExpression Id. */
  int SHA224 = 127;
  /** RegularExpression Id. */
  int SHA256 = 128;
  /** RegularExpression Id. */
  int SHA384 = 129;
  /** RegularExpression Id. */
  int SHA512 = 130;
  /** RegularExpression Id. */
  int TRUE = 131;
  /** RegularExpression Id. */
  int FALSE = 132;
  /** RegularExpression Id. */
  int DATA = 133;
  /** RegularExpression Id. */
  int INSERT = 134;
  /** RegularExpression Id. */
  int DELETE = 135;
  /** RegularExpression Id. */
  int INSERT_DATA = 136;
  /** RegularExpression Id. */
  int DELETE_DATA = 137;
  /** RegularExpression Id. */
  int DELETE_WHERE = 138;
  /** RegularExpression Id. */
  int LOAD = 139;
  /** RegularExpression Id. */
  int CLEAR = 140;
  /** RegularExpression Id. */
  int CREATE = 141;
  /** RegularExpression Id. */
  int ADD = 142;
  /** RegularExpression Id. */
  int MOVE = 143;
  /** RegularExpression Id. */
  int COPY = 144;
  /** RegularExpression Id. */
  int META = 145;
  /** RegularExpression Id. */
  int SILENT = 146;
  /** RegularExpression Id. */
  int DROP = 147;
  /** RegularExpression Id. */
  int INTO = 148;
  /** RegularExpression Id. */
  int TO = 149;
  /** RegularExpression Id. */
  int DFT = 150;
  /** RegularExpression Id. */
  int ALL = 151;
  /** RegularExpression Id. */
  int WITH = 152;
  /** RegularExpression Id. */
  int USING = 153;
  /** RegularExpression Id. */
  int DIGITS = 154;
  /** RegularExpression Id. */
  int INTEGER = 155;
  /** RegularExpression Id. */
  int DECIMAL = 156;
  /** RegularExpression Id. */
  int DOUBLE = 157;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 158;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 159;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 160;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 161;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 162;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 163;
  /** RegularExpression Id. */
  int EXPONENT = 164;
  /** RegularExpression Id. */
  int QUOTE_3D = 165;
  /** RegularExpression Id. */
  int QUOTE_3S = 166;
  /** RegularExpression Id. */
  int ECHAR = 167;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 168;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 169;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 170;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 171;
  /** RegularExpression Id. */
  int LPAREN = 172;
  /** RegularExpression Id. */
  int RPAREN = 173;
  /** RegularExpression Id. */
  int NIL = 174;
  /** RegularExpression Id. */
  int LBRACE = 175;
  /** RegularExpression Id. */
  int RBRACE = 176;
  /** RegularExpression Id. */
  int LBRACKET = 177;
  /** RegularExpression Id. */
  int RBRACKET = 178;
  /** RegularExpression Id. */
  int ANON = 179;
  /** RegularExpression Id. */
  int SEMICOLON = 180;
  /** RegularExpression Id. */
  int COMMA = 181;
  /** RegularExpression Id. */
  int DOT = 182;
  /** RegularExpression Id. */
  int EQ = 183;
  /** RegularExpression Id. */
  int NE = 184;
  /** RegularExpression Id. */
  int GT = 185;
  /** RegularExpression Id. */
  int LT = 186;
  /** RegularExpression Id. */
  int LE = 187;
  /** RegularExpression Id. */
  int GE = 188;
  /** RegularExpression Id. */
  int BANG = 189;
  /** RegularExpression Id. */
  int TILDE = 190;
  /** RegularExpression Id. */
  int COLON = 191;
  /** RegularExpression Id. */
  int SC_OR = 192;
  /** RegularExpression Id. */
  int SC_AND = 193;
  /** RegularExpression Id. */
  int PLUS = 194;
  /** RegularExpression Id. */
  int MINUS = 195;
  /** RegularExpression Id. */
  int STAR = 196;
  /** RegularExpression Id. */
  int SLASH = 197;
  /** RegularExpression Id. */
  int DATATYPE = 198;
  /** RegularExpression Id. */
  int AT = 199;
  /** RegularExpression Id. */
  int VBAR = 200;
  /** RegularExpression Id. */
  int CARAT = 201;
  /** RegularExpression Id. */
  int FPATH = 202;
  /** RegularExpression Id. */
  int RPATH = 203;
  /** RegularExpression Id. */
  int QMARK = 204;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 205;
  /** RegularExpression Id. */
  int PN_CHARS_U = 206;
  /** RegularExpression Id. */
  int PN_CHARS = 207;
  /** RegularExpression Id. */
  int PN_PREFIX = 208;
  /** RegularExpression Id. */
  int PN_LOCAL = 209;
  /** RegularExpression Id. */
  int VARNAME = 210;
  /** RegularExpression Id. */
  int UNKNOWN = 211;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<WS>",
    "<WSC>",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"distinct\"",
    "\"reduced\"",
    "\"describe\"",
    "\"construct\"",
    "\"ask\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"values\"",
    "\"undef\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"stream\"",
    "\"window\"",
    "\"range\"",
    "\"slide\"",
    "\"advance\"",
    "\"fixed\"",
    "\"triples\"",
    "\"pwindow\"",
    "\"start\"",
    "\"end\"",
    "\"register\"",
    "\"timestamp\"",
    "\"rstream\"",
    "\"dstream\"",
    "\"istream\"",
    "\"MS\"",
    "\"S\"",
    "\"HR\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"optional\"",
    "\"union\"",
    "\"minus\"",
    "\"bind\"",
    "\"service\"",
    "\"exists\"",
    "\"not\"",
    "\"as\"",
    "\"group\"",
    "\"having\"",
    "\"separator\"",
    "\"agg\"",
    "\"count\"",
    "\"min\"",
    "\"max\"",
    "\"sum\"",
    "\"avg\"",
    "\"stdev\"",
    "\"sample\"",
    "\"group_concat\"",
    "\"filter\"",
    "\"bound\"",
    "\"coalesce\"",
    "\"in\"",
    "\"if\"",
    "\"bnode\"",
    "\"iri\"",
    "\"uri\"",
    "\"str\"",
    "\"strlang\"",
    "\"strdt\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"isNumeric\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"RAND\"",
    "\"ABS\"",
    "\"CEIL\"",
    "\"FLOOR\"",
    "\"ROUND\"",
    "\"CONCAT\"",
    "\"SUBSTR\"",
    "\"STRLEN\"",
    "\"REPLACE\"",
    "\"UCASE\"",
    "\"LCASE\"",
    "\"ENCODE_FOR_URI\"",
    "\"CONTAINS\"",
    "\"STRSTARTS\"",
    "\"STRENDS\"",
    "\"STRBEFORE\"",
    "\"STRAFTER\"",
    "\"YEAR\"",
    "\"MONTH\"",
    "\"DAY\"",
    "\"HOURS\"",
    "\"MINUTES\"",
    "\"SECONDS\"",
    "\"TIMEZONE\"",
    "\"TZ\"",
    "\"NOW\"",
    "\"MD5\"",
    "\"SHA1\"",
    "\"SHA224\"",
    "\"SHA256\"",
    "\"SHA384\"",
    "\"SHA512\"",
    "\"true\"",
    "\"false\"",
    "\"data\"",
    "\"insert\"",
    "\"delete\"",
    "<INSERT_DATA>",
    "<DELETE_DATA>",
    "<DELETE_WHERE>",
    "\"load\"",
    "\"clear\"",
    "\"create\"",
    "\"add\"",
    "\"move\"",
    "\"copy\"",
    "\"meta\"",
    "\"silent\"",
    "\"drop\"",
    "\"into\"",
    "\"to\"",
    "\"default\"",
    "\"all\"",
    "\"with\"",
    "\"using\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "\"|\"",
    "\"^\"",
    "\"->\"",
    "\"<-\"",
    "\"?\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<UNKNOWN>",
  };

}
