PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> 
PREFIX qudt: <http://data.nasa.gov/qudt/owl/qudt#> 
PREFIX bicy: <http://citybikes.linkeddata.es/ontology#>  
SELECT ?avbikes ?obs ?av 
WHERE {
  ?obs a bicy:FreeBikesObservation.
  ?obs ssn:observationResult ?output.
  ?output bicy:hasAvailableBikesValue ?av.
  ?av qudt:numericValue ?avbikes.
}
