PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> 
PREFIX qudt: <http://data.nasa.gov/qudt/owl/qudt#> 
PREFIX bicy: <http://citybikes.linkeddata.es/ontology#>  
PREFIX cf-property: <http://purl.oclc.org/NET/ssnx/cf/cf-property#>
SELECT ?obs   
WHERE {
  ?obs a ssn:Observation;
       ssn:observedProperty cf-property:relative_humidity.  
}


