PREFIX cd: <http://semsorgrid4env.eu/ns#>							
PREFIX sb: <http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
SELECT ?wavets ?waveheight ?WaveObs 
#?Region
# ?lat ?lon 
FROM NAMED STREAM cd:ccometeo.srdf [NOW - 10 MINUTES TO NOW - 5 MINUTES SLIDE 3 MINUTES]
WHERE 
{ 
	?WaveObs a cd:Observation.
	{ 
		?WaveObs 	cd:observationResultTime ?wavets;
 					cd:observationResult ?waveheight. 
 	}  
 
}
		
