PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX quantity: <http://data.nasa.gov/qudt/owl/quantity#> 
SELECT ?WaveObs ?sensor
#FROM NAMED STREAM cd:ccometeo.srdf [NOW]  
WHERE
{ 
  ?WaveObs a ssn:Observation;
           ssn:observedBy ?sensor.
  SERVICE <http://someuri.com/sparql> 
  {
    ?sensor ssn:observes quantity:ThermodynamicTemperature
  }  
}								
	
