PREFIX cd: <http://semsorgrid4env.eu/ns#>							
PREFIX sb: <http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
SELECT ?wavets ?waveheight  ?waveheight2 ?wavets2
#?Region
# ?lat ?lon 
#FROM NAMED STREAM <http://semsorgrid4env.eu/ns#ccometeo.srdf> 
#[NOW - 10 MINUTE TO NOW - 5 MINUTE SLIDE 3 MINUTE] 
WHERE 
{ 
#?WaveObs a cd:Observation;
?WaveObs   cd:measuredBy cd:MilfordSensor; 
    cd:observationResult ?waveheight;   
    cd:observedProperty cd:WaveHeight;
    cd:observationResultTime ?wavets.
#?WaveObs2 a cd:Observation;
?WaveObs2   cd:observationResultTime ?wavets;
    cd:observationResult ?waveheight2;    
    cd:observedProperty cd:WaveHeightMax.
#    cd:measuredBy cd:MilfordSensor.

}
		
