PREFIX cd: <http://semsorgrid4env.eu/ns#>							
PREFIX sb: <http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
CONSTRUCT {
?WaveObs   cd:observationResult ?waveheight.
?TideObs   cd:observationResult ?tideheight.
}
FROM NAMED STREAM <http://semsorgrid4env.eu/ns#ccometeo.srdf> 
[NOW - 10 MINUTES TO NOW - 0 MINUTES] 
WHERE 
{ 
?WaveObs a cd:Observation;
   cd:observationResult ?waveheight;
   cd:measuredBy cd:HernebaySensor;
   cd:observedProperty cd:WaveHeight.
?TideObs a cd:Observation;
   cd:observationResult ?tideheight;
   cd:observedProperty cd:TideHeight.
FILTER (?tideheight<?waveheight)
}
		
