PREFIX ssg: <http://semsorgrid4env.eu/ns#>							
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX cd:  <http://www.semsorgrid4env.eu/ontologies/CoastalDefences.owl#>
PREFIX dul:	<http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX regions: <http://www.semsorgrid4env.eu/ontologies/AdditionalRegions.owl#>
CONSTRUCT 
{
	?waveobs 	a ssn:Observation;
				ssn:observationResultTime ?instant;				
				ssn:observationResult ?result; 
				ssn:featureOfInterest ?feature; 				 
			    ssg:hasLatitude ?lat;
	 			ssg:hasLongitude ?lon.
#	?feature	a ssn:FeatureOfInterest.	 		
	?instant	time:xsdDateTime ?wavets. 
	?result		ssn:hasValue ?value.
	?value		ssn:hasQuantityValue ?waveheight.
}
#FROM NAMED STREAM <http://semsorgrid4env.eu/ns#ccometeo.srdf> 
#[NOW - 10 MINUTE TO NOW - 5 MINUTE SLIDE 3 MINUTE] 
WHERE 
{ 
	?waveobs 	a ssn:Observation;
				ssn:observationResultTime ?instant;				
				ssn:observationResult ?result;  
				ssn:observedProperty cd:WaveHeight;
				ssn:featureOfInterest ?feature; 
			    ssg:hasLatitude ?lat;
	 			ssg:hasLongitude ?lon.
	?instant	time:xsdDateTime ?wavets.
	?result		ssn:hasValue ?value.
	?value		ssn:hasQuantityValue ?waveheight.
 	?feature	a ssn:FeatureOfInterest;
 				cd:locatedInRegion regions:SouthEastEnglandCCO.
	
}
		
