PREFIX ssg: <http://semsorgrid4env.eu/ns#>							
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX cd:  <http://www.semsorgrid4env.eu/ontologies/CoastalDefences.owl#>
PREFIX dul:	<http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX regions: <http://www.semsorgrid4env.eu/ontologies/AdditionalRegions.owl#>
SELECT ?wavets ?waveheight  ?WaveObs  
#FROM NAMED STREAM <http://semsorgrid4env.eu/ns#ccometeo.srdf> 
#[NOW - 10 MINUTE TO NOW - 5 MINUTE SLIDE 3 MINUTE] 
WHERE 
{ 
	?WaveObs 	a ssn:Observation;
				ssn:observationResultTime ?instant;				
				ssn:observationResult ?result;  
				ssn:observedProperty cd:WaveHeight;
				ssn:featureOfInterest ?feature. 
	?instant	time:xsdDateTime ?wavets.
	?result		ssn:hasValue ?value.
	?value		ssn:hasQuantityValue ?waveheight.
 	?feature	a ssn:FeatureOfInterest;
 				cd:locatedInRegion regions:SouthEastEnglandCCO. 
}
		
