PREFIX cd: <http://www.semsorgrid4env.eu/ontologies/CoastalDefences.owl#> 
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> 						
PREFIX sb: <http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
SELECT ?waveheight ?tideheight ?WaveObs ?TideObs
FROM NAMED STREAM <http://semsorgrid4env.eu/ns#ccometeo.srdf> 
[NOW - 10 MINUTES TO NOW - 0 MINUTES] 
WHERE 
{ 
?WaveObs a ssn:Observation;
#     ssn:observationResultTime ?wavets;     
   ssn:observationResult ?waveheight;
   ssn:observedBy cd:HernebaySensor;
     ssn:observedProperty cd:WaveHeight.
?TideObs a ssn:Observation;
#     cd:observationResultTime ?tidets;     
    ssn:observationResult ?tideheight;
     ssn:observedProperty cd:TideHeight.
FILTER (?tideheight<?waveheight)
}
		
