PREFIX cd: <http://semsorgrid4env.eu/ns#>							
PREFIX sb: <http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX time: <http://www.time.org/1999/02/22-rdf-syntax-ns#>
PREFIX ssn: <http://www.ssn.org/1999/02/22-rdf-syntax-ns#>
CONSTRUCT 
{
	?WaveObs a cd:Observation;
		cd:observationResultTime [a time:Instant;  time:inXSDDateTime ?wavets];
		cd:measuredBy ?sensor;
		cd:observationResult [ a ssn:SensorOutput;	ssn:hasResult ?waveheight].
	?sensor a cd:Sensorio.
} 
WHERE 
{ 
  ?WaveObs a cd:Observation.
  ?WaveObs  cd:observationResultTime ?wavets;
            cd:observationResult ?waveheight;
            cd:measuredBy ?sensor;               
            cd:observedProperty cd:WaveHeight.
 { ?WaveObs cd:featureOfInterest ?waveFeature. }
 ?waveFeature a cd:Feature;    
 			cd:locatedInRegion cd:SouthEastEnglandCCO.
 
}
		
